version: '3.5'

volumes:
  db_data:

services:  
    
  #DB-Server - Postgres container
  db:
    image: postgres:latest
    restart: always
    network_mode: bridge
    environment: 
        - POSTGRES_USER=prod
        - POSTGRES_PASSWORD=prod@123
        - POSTGRES_DB=db
        
    container_name: db-server
    expose:
      - 5432
    ports: 
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

       
  #Front-end server
    
  
  #Back-end Server   
  back-end-server:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: bridge
    container_name: back-end-server
    #image: rogeriodcb/productmanager:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-server:5432/db
      - TZ=America/Sao_Paulo
    expose:
      - 8080
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db